from bayes_opt import BayesianOptimization
from utils.perform_evaluation import calculate_performance
from utils.bayes_selected_strategy import pick_optimal_solution, pick_optimal_solution_ex
import numpy as np
import json
import importlib
import warnings
warnings.filterwarnings('ignore', message=".*attempting to register an np.ndarray.*")


# Load configuration.
config_path = "config.json"
with open(config_path, "r") as f:
    config = json.load(f)
bayes_iter = config["bayesian_optimization"]["n_iter"]
formula = config["settings"]["formula"]
outfile_dir = config["file_paths"]["bayes_trace"]
threshold1 = config["thresholds"]["fitness_threshold1"]
try:
    func_config = importlib.import_module(f"functions.{formula}")
except ImportError:
    raise ValueError(
        f"Configuration for '{formula}' was not found. "
        f"Please check the corresponding function file."
    )

targets = np.array(func_config.TARGET)
X0_input = func_config.X_input
Y0_input = func_config.Y_input
X_dim = len(X0_input)
Y_dim = len(Y0_input)
x_bounds = {f"x{i+1}": [row[0], row[-1]] for i, row in enumerate(func_config.X_ortho_values)}

# Global variables used during Bayesian optimization.
parameters_dir = {}
X_current = np.empty((X_dim,))
X_current0 = np.empty((X_dim,))
y_input = ''; x_input = []
X_components_list = []
Y_properties_list = []
X_bayes = []
distX = []
distY = []
range_x = np.array([vmax-vmin for vmin,vmax in list(x_bounds.values())])

    
def calculate_result(param_set):
    """
    Evaluate the objective value for a given set of input formulation parameters.
    
    Parameters
    ----------
    param_set : list of tuple
        Parameter-value pairs generated by the Bayesian optimizer, e.g.,
        [('x1', 1.58), ('x5', 2.46)].
    
    Returns
    -------
    result : float
        Objective value associated with the currently optimized response.
    """
    global range_x, X_current, X_current0, y_input, distX, distY
    
    # Update the selected variables in the current formulation.
    for k, v in param_set:
        index = int(k[1:])-1
        if index < len(X_current):
            X_current[index] = v

    Y_current = calculate_performance(X_current, Y0_input)
    Y_current0 = calculate_performance(X_current0, Y0_input)
    yi = int(y_input[1:])-1
    result = Y_current[yi]
    # Compute normalized distances in the design and response spaces.
    distX.append(round(np.sum(np.abs((X_current-X_current0)/range_x)),4))
    distY.append(round(np.sum(np.abs((Y_current-Y_current0)/targets)),4))
    
    return result

        
def black_box_function(**kwargs):
    """
    Black-box objective function used by the Bayesian optimizer.
        
    Existing observations are reused when the same parameter combination has
    already been evaluated. Otherwise, the objective value is either obtained
    from user input for experimental cases or computed automatically using the
    benchmark function.
    
    Parameters
    ----------
    **kwargs
        Design variables passed by the Bayesian optimizer.
    
    Returns
    -------
    result : float
        Scalar objective value required by the Bayesian optimization interface.
    """
    global X_bayes, distX, distY

    param_set = sorted(kwargs.items())
    param = tuple(round(value, 2) for name,value in param_set)
    try:
        result = Y_properties_list[X_components_list.index(param)]
        calculate_result(param_set)
    except ValueError:
        if formula == "experiment":
            print("The experimental parameters to be explored are: " + f'{param}')
            result = float(input("Please enter the experimental response: "))
        else:
            result = calculate_result(param_set)

    X_components_list.append(param)
    Y_properties_list.append(result)

    if isinstance(result, np.ndarray):
        return result.item()
    return result


def load_data_and_register(optimizer, X, data):
    """Register existing observations in the Bayesian optimizer."""
    
    for index, row in data.iterrows():
        try:
            row = row.tolist()
            row_values = [float(row[i]) for i in range(len(X))]
            params = dict(zip(X, row_values))
            target = float(row[-1])

            optimizer.register(params=params, target=target)
            X_components_list.append(tuple(row_values))
            Y_properties_list.append(target)

        except ValueError as e:
            print(f"Invalid row: {row}")
            print(f"Error: {e}")


def bayesian_optimize(data, X_0, xy_input, IM_matrix, Cor_matrix, fitness, mode='Dy'):
    
    global X_current, X_current0, y_input, x_input
    X_current = X_0    
    X_current0 = X_0.copy()    

    # 1) Extract the response to be optimized and its associated design variables.
    y_input, x_input = list(xy_input.keys())[0], list(xy_input.values())[0]
    pbounds = {x: x_bounds[x] for x in x_input}
    
    # 2) Initialize Bayesian optimizer.
    optimizer = BayesianOptimization(
        f=black_box_function,
        pbounds=pbounds,        
        verbose=0  # verbose = 2 prints all details, verbose = 1 prints only when a maximum is observed, verbose = 0 is silent
    )
    # Register existing reduced-dimensional data (initial orthogonal design experiments).
    load_data_and_register(optimizer, x_input, data)

    iteration = 1
    X_list_len = len(X_components_list)
    
    # 3) Run Bayesian optimization and collect candidate solutions.
    while len(X_components_list) - X_list_len < bayes_iter and iteration < 20:
        optimizer.maximize(
            init_points=0,
            n_iter=1
        )
        iteration += 1

    X_bayes = X_components_list[-bayes_iter:]
    Y_bayes = Y_properties_list[-bayes_iter:]

    # 4) Extract importance and correlation information for the selected response.
    yi = int(y_input[1:])-1
    IM_matrix, Cor_matrix = IM_matrix[yi], Cor_matrix[yi]
    selected_xi = [int(xi[1:])-1 for xi in x_input]
    IM_matrix = IM_matrix[[i for i in selected_xi]]
    Cor_matrix = Cor_matrix[[i for i in selected_xi]]
    X_selected = X_current0[[i for i in selected_xi]]
    
    # 5) Select the recommended solution according to the distance-based criterion.
    if fitness > threshold1:
        dX_current = pick_optimal_solution(
            np.array(X_bayes),
            np.array(Y_bayes),
            X_selected,
            distX,
            distY,
            xy_input,
            IM_matrix,
            Cor_matrix,
            mode=mode
        )
    else:
        dX_current = pick_optimal_solution_ex(
            np.array(X_bayes), 
            X_selected,
            xy_input,
            IM_matrix,
            Cor_matrix,
            fitness
        )
    
    return dX_current
